= Introduction to docs migration project

== Repos

We need to map the repos containing Asciidoc documentation to the modules presented by the online help UI. Several repo configurations are possible:

* A repo contains a single docs module
* A repo contains multiple docs modules
* The docs module(s) may be nested within the repo

In turn, a module in the UI can be mapped to a single repo, or draw content from multiple repos.

== Antora

Antora is the static site generator (SSG) that takes the Asciidoc content from the repos and generates a website from it, delivering the online documentation.

Antora requires a specific directory organization within the repo, and some configuration files. These details will be provided by the Technical Writer (TW).

The simplest configuration is a repo dedicated to a single module. The most basic version contains the following:

----
antora.yml
modules/
   module-example1/
      nav.adoc
      pages/
         page-content1.adoc
         ...
      assets/images
         image-content1.png
         ...
----

The *modules* folder contains one or more module folders. Each module folder contains a *pages* folder and a *nav.adoc* file.

The *pages* folder contains the Asciidoc files with the module content. It can contain a large number of pages; keep in mind that the navigation through these pages is provided by the *nav.adoc* file and is displayed in the left of the UI.
